/*
最近编写nginx模块的时候，发现worker进程老是打印:
2025/02/13 13:11:03[                 ngx_signal_handler,   927]  [notice] 32580#32580: signal 17 (SIGCHLD) received
为了定位
nginx配置方法
worker_rlimit_core  100M;
working_directory   /path/to/cores/;
注意这里一定要保证/path目录有读写权限，否则不会产生coredump文件


也可以进行系统配置，见下面:
ulimit -c 1024(限制文件大小) 或者unlimited ，这个要注意，如果不做限制，coredump文件会很大，吃掉很多磁盘空间

echo 0 > /proc/sys/kernel/core_uses_pid
echo /var/corefile/core-%e > /path/core_pattern
上面两句执行后，可以保证coredump文件为core-nginx


把core-nginx拷贝到nginx可执行文件同一目录下面

root@root:/var/yyz/corefile# gdb --core core-nginx 
GNU gdb (GDB) 7.1
Copyright (C) 2010 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "i486-slackware-linux".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
[New Thread 32581]
Core was generated by `nginx: worker'.
Program terminated with signal 11, Segmentation fault.
#0  0x0805106a in ?? ()
(gdb) bt
#0  0x0805106a in ?? ()
#1  0x00000000 in ?? ()
(gdb) file ./nginx 
warning: exec file is newer than core file.
Reading symbols from /var/yyz/corefile/nginx...done.
(gdb) bt
#0  0x0805106a in ngx_vslprintf (
    buf=0xbff2d720 "TTP_SERVER_REWRITE_PHASE)\nent_del_timer,    39]  [debug] 32581#32581: *1 < ngx_http_process_request,  2013>  event timer del: 3: 4256695641\ncess_request_headers,  1412]", 
    last=0xbff2de90 "{穦\034v衆016\b|蟎017\b匦\016\b\b唑岿o\a\b\b", fmt=<value optimized out>, 
    args=0xbff2ded4 "琓\017\b\f\b匦\016\b|蟎017\b匦\016\b\b唑縗230s\a\b匦\016\b`黒v\bl赇\003匦\016\b|蟎017\b匦\016\b(唑繝\021\a\b匦\016\b\214蟎017\b匦\016\b\b\032\020\b\b\032\020\b\220賊021\bH唑烤\022\a\b匦\016\b孛\r\b3H\f\b\b\032\020\b\220賊021\b匦\016\b蚩8\225\a\b匦\016\bべ\021\b赣Z穃020(") at src/core/ngx_string.c:332
#1  0x0804cc3d in ngx_log_error_core (level=8, log=0x80e6c88, filename=0x80c3a60 "ngx_http_core_find_config_phase", lineno=1865, err=0, fmt=0x80c3828 "find config phase: %ui (%s), uri:%V")
    at src/core/ngx_log.c:229
#2  0x08076ff9 in ngx_http_core_find_config_phase (r=0x80ed0d8, ph=0x80fcf8c) at src/http/ngx_http_core_module.c:1863
#3  0x080711a0 in ngx_http_core_run_phases (r=0x80ed0d8) at src/http/ngx_http_core_module.c:1649
#4  0x080712be in ngx_http_handler (r=0x1) at src/http/ngx_http_core_module.c:1576
#5  0x08079538 in ngx_http_process_request (r=0x80ed0d8) at src/http/ngx_http_request.c:2038
#6  0x0807ba2d in ngx_http_process_request_headers (rev=0x811d990) at src/http/ngx_http_request.c:1429
#7  0x0807bf60 in ngx_http_process_request_line (rev=0x811d990) at src/http/ngx_http_request.c:1069
#8  0x0807c558 in ngx_http_wait_request_handler (rev=0x811d990) at src/http/ngx_http_request.c:529
#9  0x0806d022 in ngx_epoll_process_events (cycle=0x80e7888, timer=20000, flags=<value optimized out>) at src/event/modules/ngx_epoll_module.c:1741
#10 0x08063e21 in ngx_process_events_and_timers (cycle=0x80e7888) at src/event/ngx_event.c:366
#11 0x0806abce in ngx_worker_process_cycle (cycle=0x80e7888, data=0x0) at src/os/unix/ngx_process_cycle.c:1069
#12 0x0806940b in ngx_spawn_process (cycle=0x80e7888, proc=0x806aad5 <ngx_worker_process_cycle>, data=0x0, name=0x80c0e7b "worker process", respawn=-3) at src/os/unix/ngx_process.c:252
#13 0x0806a082 in ngx_start_worker_processes (cycle=<value optimized out>, n=<value optimized out>, type=<value optimized out>) at src/os/unix/ngx_process_cycle.c:622
#14 0x0806b2b8 in ngx_master_process_cycle (cycle=0x80e7888) at src/os/unix/ngx_process_cycle.c:300
#15 0x0804c22f in main (argc=1, argv=0xbff2e554) at src/core/nginx.c:453
(gdb) 

*/
